services:
  quartznode:
    image: ${DOCKER_REGISTRY-}quartznode
    build:
      context: .
      dockerfile: src/QuartzNode/Dockerfile
    hostname: orchestrator
    environment:
      - FeatureManagement__OrchestratorMode=true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost/health || exit 1
      start_period: 5s
      interval: 5s
      retries: 3
      timeout: 5s

  worker1:
    build:
      context: .
      dockerfile: src/QuartzNode/Dockerfile
    container_name: worker1
    labels:
      - "com.quartznode.role=worker"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - quartznode

  worker2:
    build:
      context: .
      dockerfile: src/QuartzNode/Dockerfile
    container_name: worker2
    labels:
      - "com.quartznode.role=worker"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - quartznode

networks:
  default:
    name: local-shared
    external: true
