services:
  quartznode:
    image: ${DOCKER_REGISTRY-}quartznode
    build:
      context: .
      dockerfile: src/QuartzNode/Dockerfile
    hostname: orchestrator
    environment:
      - FeatureManagement__OrchestratorMode=true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost/health || exit 1
      start_period: 5s
      interval: 5s
      retries: 3
      timeout: 5s

  worker:
    build:
      context: .
      dockerfile: src/QuartzNode/Dockerfile
    labels:
      - "com.quartznode.role=worker"
    deploy:
      replicas: 1
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost/health || exit 1
      interval: 5s
      retries: 3
      timeout: 5s
    depends_on:
      - quartznode

networks:
  default:
    name: local-shared
    external: true
