services:

  tempo:
    image: grafana/tempo:1.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"   # otlp grpc
      - "4318"   # otlp http
      - "9411"   # zipkin
    volumes:
      - ./tempo/config/tempo.yaml:/etc/tempo.yaml:ro
      - tempo_data:/tmp/tempo

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/loki-config.yaml" ]
    environment:
      # REF https://grafana.com/docs/loki/latest/operations/troubleshooting/#enable-tracing-for-loki
      # REF https://github.com/jaegertracing/jaeger-client-go#environment-variables
      - JAEGER_AGENT_HOST=tempo 
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=const
    ports:
      - "3100"
    volumes:
      - ./loki/config/loki-local-config.yaml:/etc/loki/loki-config.yaml:ro

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=exemplar-storage
      - --web.enable-admin-api
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config/prometheus.yaml:/etc/prometheus.yaml:ro

  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  tempo_data:

networks:
  default:
    name: local-shared
    external: true