global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

scrape_configs:
  
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  
  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']
  
  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']
  
  - job_name: 'orchestrator'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ['orchestrator:443']
  
  - job_name: "workers"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
    relabel_configs:
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_docker_container_label_com_quartznode_role]
        regex: .+
        action: keep
      - source_labels: [__meta_docker_port_private]
        regex: 443
        action: keep
      # # Use the task labels that are prefixed by `prometheus-`.
      # - regex: __meta_docker_container_label_com_quartznode_(.+)
      #   action: labelmap
      #   replacement: $1
      - source_labels: ['__meta_docker_network_ip']
        regex: '/(.*)'
        target_label: 'instance'  