global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']
  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']
